tidyBooks <- function(data) {
  # data <- openxlsx::read.xlsx("data/Livres.xlsx")

  colnames(data) <- c("id", "readDate", "theme", "formatl", "origin_niv1",
                       "title", "author", "pubDate",
                       "genre_niv1", "genre_niv2", "genre_niv3", "n_pages", "lang",
                       "CNL", "ML", "MF", "GR", "BR", "BI", "prix",
                       "note", "genre_detail", "comm")

  data <- data %>%
    dplyr::select(-theme, -comm) %>%
    mutate(
      readDate = as.Date(readDate, origin = "1899-12-30"),
      formatl = relevel_factor(formatl, new.levels = list("Physique" = "Physical", "Epub" = "Epub")),
      origin_group = relevel_factor(origin_niv1, new.levels = list(
        "Amazon" = "Online Bookstore",
        "Anna's Archive" = "Web Scraping",
        "Arnaud" = "Friends & Family",
        "Bibliothèque" = "Library",
        "Enfance" = "Friends & Family",
        "epubBooks" = "Web Scraping",
        "Fnac" = "Offline Bookstore",
        "Gutenberg" = "Web Scraping",
        "Internet" = "Web Scraping",
        "Librairie" = "Offline Bookstore",
        "Liliane" = "Friends & Family",
        "Maman" = "Mom",
        "Papa" = "Dad",
        "Papou & Mamoune" = "Friends & Family",
        "Recyclerie" = "Offline Bookstore"
      )),
      origin_niv1 = relevel_factor(origin_niv1, new.levels = list(
        "Amazon" = "Amazon",
        "Anna's Archive" = "Anna's Archive",
        "Arnaud" = "Arnaud",
        "Bibliothèque" = "Library",
        "Enfance" = "Already Owned",
        "epubBooks" = "epubBooks",
        "Fnac" = "Fnac",
        "Gutenberg" = "Gutenberg",
        "Internet" = "Internet",
        "Librairie" = "Bookstore",
        "Liliane" = "Liliane",
        "Maman" = "Mom",
        "Papa" = "Dad",
        "Papou & Mamoune" = "Grandparents",
        "Recyclerie" = "Recycling Bookstore"
      )),
      genre_niv1 = as.character(relevel_factor(genre_niv1, new.levels = list(
        "Epistolaire" = "Letters",
        "Graphique" = "Graphic",
        "Non Fiction" = "Non Fiction",
        "Poétique" = "Poetic",
        "Romanesque" = "Novels",
        "Théâtral" = "Theatre"
      ))),
      genre_niv2_group = as.character(relevel_factor(genre_niv2, new.levels = list(
        "Lettres" = "Letters",
        "Bande Déssinée" = "Comics",
        "Roman Graphique" = "Graphic Novels",
        "Album" = "Albums",
        "Poème" = "Poems",
        "Recueil de poèmes" = "Poems",
        "Conte" = "Tales",
        "Recueil de contes" = "Tales",
        "Nouvelle" = "Short stories",
        "Recueil de nouvelles" = "Short stories",
        "Recueil de séances" = "Short stories",
        "Roman" = "Novels",
        "Roman Court" = "Novels",
        "Poème Epique" = "Epics",
        "Epopée" = "Epics",
        "Comédie" = "Comedies",
        "Comédie grecque" = "Comedies",
        "Tragédie" = "Tragedies",
        "Tragédie grecque" = "Tragedies",
        "Drame" = "Dramas",
        "Discours & Plaidoyer" = "Speech, pamphlets...",
        "Pamphlet & Satire" = "Speech, pamphlets...",
        "Autobiographie" = "Biographies & Autobiographies",
        "Biographie" = "Biographies & Autobiographies",
        "Livre de Référence" = "Reference, treaties...",
        "Traité" = "Reference, treaties...",
        "Essai" = "Essay",
        "Dialogue" = "Essay",
        "Pensées" = "Essay"
      ))),
      genre_niv2_group = ifelse(is.na(genre_niv2_group), genre_niv2, genre_niv2_group),
      genre_niv2 = as.character(relevel_factor(genre_niv2, new.levels = list(
        "Lettres" = "Letters",
        "Bande Déssinée" = "Comics",
        "Roman Graphique" = "Graphic Novels",
        "Album" = "Albums",
        "Poème" = "Poems",
        "Recueil de poèmes" = "Collection of poems",
        "Conte" = "Tales",
        "Recueil de contes" = "Collection of tales",
        "Nouvelle" = "Short stories",
        "Recueil de nouvelles" = "Collection of short stories",
        "Recueil de séances" = "Collection of sessions",
        "Roman" = "Novels",
        "Roman Court" = "Short novels",
        "Poème Epique" = "Epics",
        "Epopée" = "Epics",
        "Comédie" = "Comedies",
        "Comédie grecque" = "Greek comedies",
        "Tragédie" = "Tragedies",
        "Tragédie grecque" = "Greek tragedies",
        "Drame" = "Dramas",
        "Discours & Plaidoyer" = "Speech & Advocacies",
        "Pamphlet & Satire" = "Satire & Pamphlets",
        "Autobiographie" = "Autobiographies",
        "Biographie" = "Biographies",
        "Livre de Référence" = "Reference books",
        "Traité" = "Treaties",
        "Essai" = "Essay",
        "Dialogue" = "Dialogues",
        "Pensées" = "Thoughts"
      ))),
      lang = relevel_factor(lang, new.levels = list("Français" = "French", "Anglais" = "English")),
      note = as.numeric(note)
      )
}
